# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 582)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnQuit = QtWidgets.QPushButton(self.frame)
        self.btnQuit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnQuit.setFont(font)
        self.btnQuit.setFlat(False)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout_2.addWidget(self.btnQuit)
        self.btnLoad = QtWidgets.QPushButton(self.frame)
        self.btnLoad.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLoad.setFont(font)
        self.btnLoad.setFlat(False)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_2.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setFlat(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAdd.setFont(font)
        self.btnAdd.setFlat(False)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(self.frame)
        self.btnEdit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setFlat(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout_2.addWidget(self.btnEdit)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setBaseSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fmPollRates = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fmPollRates.sizePolicy().hasHeightForWidth())
        self.fmPollRates.setSizePolicy(sizePolicy)
        self.fmPollRates.setMinimumSize(QtCore.QSize(0, 100))
        self.fmPollRates.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fmPollRates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmPollRates.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmPollRates.setObjectName("fmPollRates")
        self.formLayout = QtWidgets.QFormLayout(self.fmPollRates)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblServPoll = QtWidgets.QLabel(self.fmPollRates)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblServPoll.setFont(font)
        self.lblServPoll.setObjectName("lblServPoll")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblServPoll)
        self.label_2 = QtWidgets.QLabel(self.fmPollRates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.hlineSep = QtWidgets.QFrame(self.fmPollRates)
        self.hlineSep.setMinimumSize(QtCore.QSize(100, 0))
        self.hlineSep.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hlineSep.setLineWidth(1)
        self.hlineSep.setFrameShape(QtWidgets.QFrame.HLine)
        self.hlineSep.setObjectName("hlineSep")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hlineSep)
        self.gridLayout_3.addWidget(self.fmPollRates, 1, 0, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_3.addWidget(self.btnStop, 0, 0, 1, 1)
        self.gbPinnedPlot = QtWidgets.QGroupBox(self.frame_3)
        self.gbPinnedPlot.setMinimumSize(QtCore.QSize(250, 250))
        self.gbPinnedPlot.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbPinnedPlot.setFont(font)
        self.gbPinnedPlot.setObjectName("gbPinnedPlot")
        self.gridLayout_3.addWidget(self.gbPinnedPlot, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.tabMain = QtWidgets.QTabWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMinimumSize(QtCore.QSize(700, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabMain.setFont(font)
        self.tabMain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabMain.setObjectName("tabMain")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabMain.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabMain.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabMain.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabMain.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabMain)
        self.tabMain.raise_()
        self.frame_3.raise_()
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ion Source Control System"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.btnLoad.setText(_translate("MainWindow", "Load Device from File"))
        self.btnSave.setText(_translate("MainWindow", "Save Devices"))
        self.btnAdd.setText(_translate("MainWindow", "Add Device/Channel"))
        self.btnEdit.setText(_translate("MainWindow", "Edit Device/Channel"))
        self.lblServPoll.setText(_translate("MainWindow", "Server Polling Rate: 15 Hz"))
        self.label_2.setText(_translate("MainWindow", "Device 1 Polling Rate: 15 Hz"))
        self.btnStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.gbPinnedPlot.setTitle(_translate("MainWindow", "Pinned Plot"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab), _translate("MainWindow", "Overview"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_2), _translate("MainWindow", "Plotting"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_3), _translate("MainWindow", "Settings"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_4), _translate("MainWindow", "Message Log"))

