# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 641)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnQuit = QtWidgets.QPushButton(self.frame)
        self.btnQuit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnQuit.setFont(font)
        self.btnQuit.setFlat(False)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout.addWidget(self.btnQuit)
        self.btnLoad = QtWidgets.QPushButton(self.frame)
        self.btnLoad.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLoad.setFont(font)
        self.btnLoad.setFlat(False)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setFlat(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAdd.setFont(font)
        self.btnAdd.setFlat(False)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(self.frame)
        self.btnEdit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setFlat(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        self.verticalLayout.addWidget(self.frame)
        self.splitter_2 = QtWidgets.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setBaseSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_3.addWidget(self.btnStop, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.fmPollRates = QtWidgets.QFrame(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fmPollRates.sizePolicy().hasHeightForWidth())
        self.fmPollRates.setSizePolicy(sizePolicy)
        self.fmPollRates.setMinimumSize(QtCore.QSize(0, 100))
        self.fmPollRates.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fmPollRates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmPollRates.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmPollRates.setObjectName("fmPollRates")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fmPollRates)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblServPoll = QtWidgets.QLabel(self.fmPollRates)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblServPoll.setFont(font)
        self.lblServPoll.setObjectName("lblServPoll")
        self.verticalLayout_2.addWidget(self.lblServPoll)
        self.label_2 = QtWidgets.QLabel(self.fmPollRates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gbPinnedPlot = QtWidgets.QGroupBox(self.splitter_3)
        self.gbPinnedPlot.setMinimumSize(QtCore.QSize(0, 250))
        self.gbPinnedPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbPinnedPlot.setFont(font)
        self.gbPinnedPlot.setObjectName("gbPinnedPlot")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbPinnedPlot)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pltPinned = PlotWidget(self.gbPinnedPlot)
        self.pltPinned.setObjectName("pltPinned")
        self.gridLayout_7.addWidget(self.pltPinned, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_3, 1, 0, 1, 1)
        self.tabMain = QtWidgets.QTabWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMinimumSize(QtCore.QSize(500, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabMain.setFont(font)
        self.tabMain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabMain.setObjectName("tabMain")
        self.overview = QtWidgets.QWidget()
        self.overview.setObjectName("overview")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.overview)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fmOverview = QtWidgets.QFrame(self.overview)
        self.fmOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmOverview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmOverview.setObjectName("fmOverview")
        self.gridLayout_2.addWidget(self.fmOverview, 0, 0, 1, 1)
        self.tabMain.addTab(self.overview, "")
        self.devices = QtWidgets.QWidget()
        self.devices.setObjectName("devices")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.devices)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(self.devices)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.columnView = QtWidgets.QColumnView(self.splitter)
        self.columnView.setMinimumSize(QtCore.QSize(100, 0))
        self.columnView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.columnView.setObjectName("columnView")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabMain.addTab(self.devices, "")
        self.plotting = QtWidgets.QWidget()
        self.plotting.setObjectName("plotting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.plotting)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pltDefault = PlotWidget(self.plotting)
        self.pltDefault.setObjectName("pltDefault")
        self.gridLayout_5.addWidget(self.pltDefault, 0, 0, 1, 1)
        self.tabMain.addTab(self.plotting, "")
        self.procedures = QtWidgets.QWidget()
        self.procedures.setObjectName("procedures")
        self.tabMain.addTab(self.procedures, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.gridLayout = QtWidgets.QGridLayout(self.log)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.txtMessageLog = QtWidgets.QTextEdit(self.log)
        self.txtMessageLog.setReadOnly(True)
        self.txtMessageLog.setObjectName("txtMessageLog")
        self.gridLayout.addWidget(self.txtMessageLog, 0, 0, 1, 1)
        self.tabMain.addTab(self.log, "")
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ion Source Control System"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.btnLoad.setText(_translate("MainWindow", "Load Device from File"))
        self.btnSave.setText(_translate("MainWindow", "Save Devices"))
        self.btnAdd.setText(_translate("MainWindow", "Add Device/Channel"))
        self.btnEdit.setText(_translate("MainWindow", "Edit Device/Channel"))
        self.btnStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.lblServPoll.setText(_translate("MainWindow", "Server Polling Rate: 15 Hz"))
        self.label_2.setText(_translate("MainWindow", "Device 1 Polling Rate: 15 Hz"))
        self.gbPinnedPlot.setTitle(_translate("MainWindow", "Pinned Plot"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.overview), _translate("MainWindow", "Overview"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.devices), _translate("MainWindow", "Devices"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.plotting), _translate("MainWindow", "Plotting"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.procedures), _translate("MainWindow", "Procedures"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.log), _translate("MainWindow", "Message Log"))

from pyqtgraph import PlotWidget
