# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ProcedureDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProcedureDialog(object):
    def setupUi(self, ProcedureDialog):
        ProcedureDialog.setObjectName("ProcedureDialog")
        ProcedureDialog.resize(855, 735)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        ProcedureDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcedureDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(ProcedureDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.txtProcedureName = QtWidgets.QLineEdit(ProcedureDialog)
        self.txtProcedureName.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProcedureName.setObjectName("txtProcedureName")
        self.horizontalLayout_7.addWidget(self.txtProcedureName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.groupBox_2 = QtWidgets.QGroupBox(ProcedureDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbRuleDevice = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleDevice.setCurrentText("")
        self.cbRuleDevice.setObjectName("cbRuleDevice")
        self.horizontalLayout_5.addWidget(self.cbRuleDevice)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.cbRuleChannel = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleChannel.setCurrentText("")
        self.cbRuleChannel.setObjectName("cbRuleChannel")
        self.horizontalLayout_5.addWidget(self.cbRuleChannel)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cbRuleCompare = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleCompare.setCurrentText("")
        self.cbRuleCompare.setObjectName("cbRuleCompare")
        self.horizontalLayout_5.addWidget(self.cbRuleCompare)
        self.cbRuleBool = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleBool.setObjectName("cbRuleBool")
        self.horizontalLayout_5.addWidget(self.cbRuleBool)
        self.txtRuleVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtRuleVal.setObjectName("txtRuleVal")
        self.horizontalLayout_5.addWidget(self.txtRuleVal)
        self.lblRuleUnit = QtWidgets.QLabel(self.groupBox_2)
        self.lblRuleUnit.setObjectName("lblRuleUnit")
        self.horizontalLayout_5.addWidget(self.lblRuleUnit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(ProcedureDialog)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 475))
        self.groupBox_3.setObjectName("groupBox_3")
        self.vboxAction = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.vboxAction.setObjectName("vboxAction")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.cbActionDevice = QtWidgets.QComboBox(self.groupBox_3)
        self.cbActionDevice.setCurrentText("")
        self.cbActionDevice.setObjectName("cbActionDevice")
        self.horizontalLayout_8.addWidget(self.cbActionDevice)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.cbActionChannel = QtWidgets.QComboBox(self.groupBox_3)
        self.cbActionChannel.setCurrentText("")
        self.cbActionChannel.setObjectName("cbActionChannel")
        self.horizontalLayout_8.addWidget(self.cbActionChannel)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cbActionBool = QtWidgets.QComboBox(self.groupBox_3)
        self.cbActionBool.setObjectName("cbActionBool")
        self.horizontalLayout_8.addWidget(self.cbActionBool)
        self.txtActionVal = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtActionVal.setObjectName("txtActionVal")
        self.horizontalLayout_8.addWidget(self.txtActionVal)
        self.lblActionUnit = QtWidgets.QLabel(self.groupBox_3)
        self.lblActionUnit.setObjectName("lblActionUnit")
        self.horizontalLayout_8.addWidget(self.lblActionUnit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.btnAddAction = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAddAction.setObjectName("btnAddAction")
        self.horizontalLayout_8.addWidget(self.btnAddAction)
        self.vboxAction.addLayout(self.horizontalLayout_8)
        self.scAction = QtWidgets.QScrollArea(self.groupBox_3)
        self.scAction.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scAction.setWidgetResizable(True)
        self.scAction.setObjectName("scAction")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fmActions = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.fmActions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmActions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmActions.setObjectName("fmActions")
        self.gridLayout.addWidget(self.fmActions, 0, 0, 1, 1)
        self.scAction.setWidget(self.scrollAreaWidgetContents)
        self.vboxAction.addWidget(self.scAction)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(ProcedureDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkCritical = QtWidgets.QCheckBox(self.groupBox)
        self.chkCritical.setObjectName("chkCritical")
        self.horizontalLayout.addWidget(self.chkCritical)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(ProcedureDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chkEmail = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkEmail.setObjectName("chkEmail")
        self.horizontalLayout_6.addWidget(self.chkEmail)
        self.chkText = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkText.setObjectName("chkText")
        self.horizontalLayout_6.addWidget(self.chkText)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gbContact = QtWidgets.QGroupBox(ProcedureDialog)
        self.gbContact.setObjectName("gbContact")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbContact)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblEmail = QtWidgets.QLabel(self.gbContact)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout_2.addWidget(self.lblEmail, 0, 1, 1, 1)
        self.lblText = QtWidgets.QLabel(self.gbContact)
        self.lblText.setObjectName("lblText")
        self.gridLayout_2.addWidget(self.lblText, 1, 1, 1, 1)
        self.txtText = QtWidgets.QLineEdit(self.gbContact)
        self.txtText.setObjectName("txtText")
        self.gridLayout_2.addWidget(self.txtText, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.gbContact)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout_2.addWidget(self.txtEmail, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.gbContact)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.btnDone = QtWidgets.QPushButton(ProcedureDialog)
        self.btnDone.setObjectName("btnDone")
        self.horizontalLayout_2.addWidget(self.btnDone)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ProcedureDialog)
        QtCore.QMetaObject.connectSlotsByName(ProcedureDialog)

    def retranslateUi(self, ProcedureDialog):
        _translate = QtCore.QCoreApplication.translate
        ProcedureDialog.setWindowTitle(_translate("ProcedureDialog", "Add/Edit Procedure"))
        self.label.setText(_translate("ProcedureDialog", "Name"))
        self.txtProcedureName.setText(_translate("ProcedureDialog", "My Procedure"))
        self.groupBox_2.setTitle(_translate("ProcedureDialog", "Rule"))
        self.label_3.setText(_translate("ProcedureDialog", "."))
        self.label_4.setText(_translate("ProcedureDialog", "is"))
        self.lblRuleUnit.setText(_translate("ProcedureDialog", "TextLabel"))
        self.groupBox_3.setTitle(_translate("ProcedureDialog", "Action"))
        self.label_2.setText(_translate("ProcedureDialog", "Set"))
        self.label_5.setText(_translate("ProcedureDialog", "."))
        self.label_6.setText(_translate("ProcedureDialog", "to"))
        self.lblActionUnit.setText(_translate("ProcedureDialog", "TextLabel"))
        self.btnAddAction.setText(_translate("ProcedureDialog", "Add"))
        self.groupBox.setTitle(_translate("ProcedureDialog", "Options"))
        self.chkCritical.setText(_translate("ProcedureDialog", "Critical"))
        self.groupBox_4.setTitle(_translate("ProcedureDialog", "Notify"))
        self.chkEmail.setText(_translate("ProcedureDialog", "Email"))
        self.chkText.setText(_translate("ProcedureDialog", "Text"))
        self.gbContact.setTitle(_translate("ProcedureDialog", "Contact Information"))
        self.lblEmail.setText(_translate("ProcedureDialog", "Email"))
        self.lblText.setText(_translate("ProcedureDialog", "Mobile"))
        self.btnDone.setText(_translate("ProcedureDialog", "Done"))

