# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/PlotSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotSettingsDialog(object):
    def setupUi(self, PlotSettingsDialog):
        PlotSettingsDialog.setObjectName("PlotSettingsDialog")
        PlotSettingsDialog.resize(505, 384)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        PlotSettingsDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(PlotSettingsDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbXAuto = QtWidgets.QRadioButton(self.groupBox)
        self.rbXAuto.setObjectName("rbXAuto")
        self.horizontalLayout.addWidget(self.rbXAuto)
        self.rbXManual = QtWidgets.QRadioButton(self.groupBox)
        self.rbXManual.setObjectName("rbXManual")
        self.horizontalLayout.addWidget(self.rbXManual)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.txtXMin = QtWidgets.QLineEdit(self.groupBox)
        self.txtXMin.setObjectName("txtXMin")
        self.verticalLayout_3.addWidget(self.txtXMin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtXMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtXMax.setObjectName("txtXMax")
        self.verticalLayout_2.addWidget(self.txtXMax)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(PlotSettingsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbYAuto = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbYAuto.setObjectName("rbYAuto")
        self.horizontalLayout_2.addWidget(self.rbYAuto)
        self.rbYManual = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbYManual.setObjectName("rbYManual")
        self.horizontalLayout_2.addWidget(self.rbYManual)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.txtYMin = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtYMin.setObjectName("txtYMin")
        self.verticalLayout_4.addWidget(self.txtYMin)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.txtYMax = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtYMax.setObjectName("txtYMax")
        self.verticalLayout_5.addWidget(self.txtYMax)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnColor = QtWidgets.QPushButton(PlotSettingsDialog)
        self.btnColor.setObjectName("btnColor")
        self.horizontalLayout_4.addWidget(self.btnColor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnDone = QtWidgets.QPushButton(PlotSettingsDialog)
        self.btnDone.setObjectName("btnDone")
        self.horizontalLayout_3.addWidget(self.btnDone)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(PlotSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(PlotSettingsDialog)

    def retranslateUi(self, PlotSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PlotSettingsDialog.setWindowTitle(_translate("PlotSettingsDialog", "Edit Plot Settings"))
        self.groupBox.setTitle(_translate("PlotSettingsDialog", "X-Axis Limits"))
        self.rbXAuto.setText(_translate("PlotSettingsDialog", "Auto"))
        self.rbXManual.setText(_translate("PlotSettingsDialog", "Manual"))
        self.label.setText(_translate("PlotSettingsDialog", "Min"))
        self.label_2.setText(_translate("PlotSettingsDialog", "Max"))
        self.groupBox_2.setTitle(_translate("PlotSettingsDialog", "Y-Axis Limits"))
        self.rbYAuto.setText(_translate("PlotSettingsDialog", "Auto"))
        self.rbYManual.setText(_translate("PlotSettingsDialog", "Manual"))
        self.label_3.setText(_translate("PlotSettingsDialog", "Min"))
        self.label_4.setText(_translate("PlotSettingsDialog", "Max"))
        self.btnColor.setText(_translate("PlotSettingsDialog", "Color..."))
        self.btnDone.setText(_translate("PlotSettingsDialog", "Done"))

